### ISSUE TITLE
运行main.py在dataloder_video.py中遇到问题

### ISSUE THREAD

**Issue by zhouinging** [hulianyuyy/Temporal-Lift-Pooling#10]
Loading model finished.
Loading data
train 7096
Apply training transform.
train 7096
Apply testing transform.
dev 519
Apply testing transform.
test 642
Apply testing transform.
Loading data finished.
.git does not exist in current dir
[ Fri Nov 15 09:47:11 2024 ] Parameters:
{'work_dir': './work_dir/baseline_resnet18_liftpool/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '0,1,2', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 200, 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './dataset/phoenix2014-T', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 8, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'prefix': './dataset/phoenix2014-T', 'transform_mode': False, 'dataset': 'phoenix2014-T'}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 2, 'test_batch_size': 2, 'loss_weights': {'ConvCTC': 1.0, 'SeqCTC': 1.0, 'Dist': 25.0, 'Cu': 0.001, 'Cp': 0.001}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [40, 60], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 80}

Traceback (most recent call last):
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/main.py", line 248, in <module>
    processor.start()
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/main.py", line 66, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/seq_scripts.py", line 23, in seq_train
    for batch_idx, data in enumerate(loader):
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/ExtHDD2/zxn/Anaconda3/envs/TLP/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/dataset/dataloader_video.py", line 50, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/dataset/dataloader_video.py", line 83, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/utils/video_augmentation.py", line 24, in __call__
    image = t(image)
  File "/media/ExtHDD2/zxn/Temporal-Lift-Poooling-main/utils/video_augmentation.py", line 119, in __call__
    if isinstance(clip[0], np.ndarray):
IndexError: list index out of range

**Comment by hulianyuyy** [comment]
This is mostly caused by that you don't set a correct soft link to the dataset path. You may print the `clip` variable in line 119 in [utils/video_augmentation.py](https://github.com/hulianyuyy/Temporal-Lift-Pooling/blob/main/utils/video_augmentation.py) to check if it is None.

**Comment by zhouinging** [comment]
> 这主要是因为你没有设置正确的数据集路径软链接，你可以打印[utils/video_augmentation.py](https://github.com/hulianyuyy/Temporal-Lift-Pooling/blob/main/utils/video_augmentation.py)`clip`中第 119 行的变量来检查它是否为 None。[](https://github.com/hulianyuyy/Temporal-Lift-Pooling/blob/main/utils/video_augmentation.py)
但是设置数据集软链接时并没有报错，成功并调整了图像序列的大小

**Comment by hulianyuyy** [comment]
What do you mean by successfully adjust the size of image sequences? Do you mean that you successfully run the preprocess.py and successfully resize the images?

**Comment by zhouinging** [comment]
> What do you mean by successfully adjust the size of image sequences? Do you mean that you successfully run the preprocess.py and successfully resize the images?
是的

**Comment by hulianyuyy** [comment]
After that, you should craete a soft link like we demonstrate in the readme.md, so that your code could read the videos. Maybe the problem is that you have resized the images but set wrong soft link and the code can't find the videos.

**Comment by zhouinging** [comment]
> What do you mean by successfully adjust the size of image sequences? Do you mean that you successfully run the preprocess.py and successfully resize the 我是初学者，希望您指导一下。
[Uploading problems.docx…]()

**Comment by hulianyuyy** [comment]
I failed to view your problems.docx when fails to be uploaded.

**Comment by zhouinging** [comment]
[problems.docx](https://github.com/user-attachments/files/17800202/problems.docx)
也许我在创建软链接时候出了问题，我正在探索中，谢谢您的帮助

**Comment by hulianyuyy** [comment]
As shown in the readme.md, we ask you to conduct a command `ln -s PATH_TO_DATASET/phoenix2014-release ./dataset/phoenix2014`. Could you paste your command that you have conducted here?

**Comment by zhouinging** [comment]
![image](https://github.com/user-attachments/assets/1510ba2f-6db9-4966-8d3f-977771ce723e)

**Comment by hulianyuyy** [comment]
You should first conduct `unlink ./dataset/phoenix2014`, and then conduct `ln -s /media/ExtHDD1/phoenix2014/phoenix2014-release ./dataset/phoenix2014`. Then you should successfully run the code.
