### ISSUE TITLE
Error in DataLoader_video.py

### ISSUE THREAD

**Issue by mohiburnabil** [hulianyuyy/Temporal-Lift-Pooling#9]
when I run the main.py it gives me 
**NameError: name 'kernel_sizes' is not defined** error
here is the full error message:
Traceback (most recent call last):
  File "C:\Users\mohib\OneDrive\Desktop\Temporal-Lift-Pooling-main - Copy\Temporal-Lift-Pooling-main\main.py", line 249, in <module>
    processor.start()
  File "C:\Users\mohib\OneDrive\Desktop\Temporal-Lift-Pooling-main - Copy\Temporal-Lift-Pooling-main\main.py", line 65, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "C:\Users\mohib\OneDrive\Desktop\Temporal-Lift-Pooling-main - Copy\Temporal-Lift-Pooling-main\seq_scripts.py", line 23, in seq_train
    for batch_idx, data in enumerate(loader):
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
NameError: Caught NameError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\mohib\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "C:\Users\mohib\OneDrive\Desktop\Temporal-Lift-Pooling-main - Copy\Temporal-Lift-Pooling-main\dataset\dataloader_video.py", line 125, in collate_fn
    for layer_idx, ks in enumerate(kernel_sizes):
NameError: name 'kernel_sizes' is not defined

Process finished with exit code 1

**Comment by hulianyuyy** [comment]
The 'kernel_sizes' is defined as a global vector in DataLoader_video.py. Besides, 'for layer_idx, ks in enumerate(kernel_sizes):' appears in line 123 in DataLoader_video.py, while yours appears in line 125 in DataLoader_video.py. Maybe these is something that has been changed? You could give me feedback further.

**Comment by zhouinging** [comment]
> 'kernel_sizes' 在 DataLoader_video.py 中定义为全局向量。此外，'for layer_idx, ks in enumerate(kernel_sizes):' 出现在 DataLoader_video.py 的第 123 行，而您的出现在 DataLoader_video.py 的第 125 行。也许这些是已经更改的内容？您可以进一步给我反馈。

可以具体描述吗？我也遇到了同样的问题
